# Datastructures

1. LISTS
2. TUPLE
3. SET
4. DICTIONARY

In [5]:
L = [3, "JOSEPH", 45.6, "kiran", "joseph"]
T = (3, "JOSEPH", 45.6, "kiran", "joseph")
S=  {3, "JOSEPH", 45.6, "kiran", "joseph"}
D = {1: "KAMBHAM", 2:"JOSEPH", 3:"NAVEEN", 4: "KIRAN", "C": "JOSEPH"}

In [16]:
print(L)
L[3]

[3, 'JOSEPH', 45.6, 'kiran', 'Joseph', 'kiran']


'kiran'

In [7]:
print(T)

(3, 'JOSEPH', 45.6, 'kiran', 'joseph')


In [8]:
T[3]

'kiran'

In [13]:
L.append("kiran")

In [15]:
L[4] = "Joseph"

In [17]:
print(S)

{3, 'joseph', 'JOSEPH', 45.6, 'kiran'}


In [18]:
"kiran" in S

True

In [25]:
D

{1: 'KAMBHAM',
 2: 'JOSEPH',
 3: 'NAVEEN',
 4: 'KIRAN',
 'C': 'JOSEPH',
 5: 'Christy'}

In [45]:
D[5] ='Christy'
D
print(D.keys())
print(D.values())


dict_keys([1, 2, 3, 4, 'C', 5])
dict_values(['KAMBHAM', 'JOSEPH', 'NAVEEN', 'KIRAN', 'JOSEPH', 'Christy'])


In [22]:
dict?

In [32]:
L[0:4:1]

[3, 'JOSEPH', 45.6, 'kiran']

In [46]:
L2 = [43,99.8, "jay", "bpahrm"]

In [48]:
L3 = L+L2
print(L3)

[3, 'JOSEPH', 45.6, 'kiran', 'Joseph', 'kiran', 43, 99.8, 'jay', 'bpahrm']


In [51]:
list_add_1 = [34,45,65.7,3]
list_add_2 = [32,36,57,80,90]
L4 = [x + y for x,y in zip(list_add_1,list_add_2)]
print(L4)

[66, 81, 122.7, 83]


In [53]:
import random
random.randint(1,6)

5

In [9]:
import numpy as np

def computer_choice():
    return np.random.randint(1,7)

def user_choice():
    print(f"Hello,You are now playing Dice game")
    print(f" Please select numbers between 1 and 6")
    user_chosen = int(input())
    if 1 <= user_chosen <= 6:
        computer_chosen = computer_choice()
        if user_chosen == computer_chosen:
            print("You made a correct guess")
        else:
            print(f"Try again, correct number was {computer_chosen}")
            
    else:
        print("Please choose between 1 and 6")

while True:
    user_choice()
    break

Hello,You are now playing Dice game
 Please select numbers between 1 and 6
4
Try again, correct number was 6


In [12]:
def getstudentmarks():
    D = {}
    while True:
       
        student_id = input("Enter student id: ")
        student_marks = input ("Enter student marks splitted by ,: ")
        more_student = input("Enter NO to quit insertion or print anything")
    
        if student_id in D:
            print("Already student is avaiable")
        else:
            D[student_id] = student_marks.split(',')
    
        if more_student.lower() == 'no':
            print("Thanks for adding students")
            return D
    

insert_students = getstudentmarks()

Enter student id: 1
Enter student marks splitted by ,: 45,67,89
Enter NO to quit insertion or print anything34
Enter student id: 2
Enter student marks splitted by ,: 67,89,90
Enter NO to quit insertion or print anything56
Enter student id: 3
Enter student marks splitted by ,: 23,99,100
Enter NO to quit insertion or print anythingNO
Thanks for adding students


In [13]:
print(insert_students)

{'1': ['45', '67', '89'], '2': ['67', '89', '90'], '3': ['23', '99', '100']}


In [9]:
print(D)

NameError: name 'D' is not defined

In [27]:
def calculate_average(D):
    average_marks ={}
    for x in D:
        L = D[x]
        s = 0
        for marks in L:
            s+=int(marks)
        average_marks[x] = s/len(L)
    return average_marks
        
        

In [28]:
avgm = calculate_average(insert_students)

In [29]:
for x in avgm:
    print(f"Student id {x} has average marks of :", avgm[x])

Student id 1 has average marks of : 67.0
Student id 2 has average marks of : 82.0
Student id 3 has average marks of : 74.0


In [31]:
import numpy as np

In [32]:
a = np.array([[1,2] , [3,4]])

In [33]:
a

array([[1, 2],
       [3, 4]])

In [34]:
b = np.array([6,7])

In [35]:
b

array([6, 7])

In [36]:
a.ndim

2

In [37]:
b.ndim

1

In [38]:
a.shape

(2, 2)

In [39]:
a.dtype

dtype('int64')

In [40]:
b.dtype

dtype('int64')

In [41]:
a + b

array([[ 7,  9],
       [ 9, 11]])

In [43]:
print(a.data)

In [46]:
c = np.array([[[1,2],[3,4]], [[6,7],[8,9]], [[3,6],[7,8]]])

In [47]:
c.shape

(3, 2, 2)

In [48]:
c

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]],

       [[3, 6],
        [7, 8]]])

In [49]:
c.size

12

In [51]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
np.arange(2,19)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [53]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [59]:
np.random.permutation(np.arange(10))

array([0, 3, 4, 1, 9, 5, 2, 8, 6, 7])

In [61]:
np.random.randint(1,10)

6

In [62]:
np.array_str?

In [63]:
np.array_str(np.arange(3))

'[0 1 2]'

In [65]:
np.broadcast?

In [67]:
np.tri?

In [68]:
np.reshape?